name: CD Global Terraform

on:
  push:
    branches: [ master ]
    paths:
      - 'iac/global/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'iac/global/**'

jobs:
  cd-global-terraform:
    uses: ./.github/workflows/reusable-terraform-cd.yml
    with:
      terraform-path: 'iac/global/route53'
      node-version: '20'
