name: CI & CD Admin backend 

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
      - 'iac/backend/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'backend/**'
      - 'iac/backend/**'
jobs:
  ci-admin-backend:
    uses: ./.github/workflows/reusable-backend-ci.yml
    with:
      backend-path: 'backend'
      node-version: '20'

  ci-admin-backend-terraform:
    uses: ./.github/workflows/reusable-terraform-ci.yml
    with:
      terraform-path: 'iac/backend'

  cd-admin-backend-terraform:
    needs: ci-admin-backend-terraform
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-terraform-cd.yml
    with:
      terraform-path: 'iac/backend'
      env-vars: '{"ENV":"production","REGION":"us-east-1","DEBUG":"false"}'
      branch-name: ${{ github.ref_name }}
      lambda-zip-path: 'admin-api-lambda'
    secrets:
      TF_VAR_DATABASE_URL: ${{ secrets.DATABASE_URL }}
