name: CI & CD Admin frontend 

on:
  push:
    branches: [ master ]
    paths:
      - 'frontends/admin/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'frontends/admin/**'
  workflow_dispatch:

jobs:
  ci-admin-frontend:
    uses: ./.github/workflows/reusable-frontend-ci.yml
    with:
      frontend-path: 'admin-frontend'
      node-version: '20'
  
  cd-admin-frontend:
    permissions:
      id-token: write
      contents: read
    needs: ci-admin-frontend
    uses: ./.github/workflows/reusable-frontend-cd.yml
    with:
      frontend-path: 'frontends/admin'
      node-version: '20'
      cloudfront-distribution-id: 'E2Q2BA3Q2EDJ7'
      s3-bucket-url: 's3://production-menapp-admin-frontend'
      branch-name: ${{ github.ref_name }}

  
