name: CI & CD Admin backend 

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
      - 'iac/backend/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'backend/**'
      - 'iac/backend/**'
jobs:
  ci-admin-backend:
    uses: ./.github/workflows/reusable-backend-ci.yml
    with:
      backend-path: 'backend'
      node-version: '20'

  cd-admin-backend:
    needs: ci-admin-backend
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-backend-cd.yml
    with:
      backend-path: 'backend'
      node-version: '20'
      branch-name: ${{ github.ref_name }}
      s3-bucket-url: 's3://menupp-production-lambda-deployment'
      lambda-zip-path: 'admin-api-lambda'
      env-vars: '{"ENV":"production","REGION":"us-east-1","DEBUG":"false"}'

