name: CI & CD Admin backend 

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
      - 'iac/backend/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'backend/**'
      - 'iac/backend/**'

jobs:
  ci-admin-backend:
    uses: ./.github/workflows/reusable-backend-ci.yml
    with:
      backend-path: 'backend'
      node-version: '20'

  cd-admin-backend:
    needs: ci-admin-backend
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-backend-cd.yml
    with:
      image-path: 'backend'
      image-uri: '084519756118.dkr.ecr.us-east-1.amazonaws.com/admin-api-lambda'
      branch-name: ${{ github.ref_name }}
      env-vars: '{"ENV":"production","REGION":"us-east-1","DEBUG":"false"}'

  ci-admin-backend-terraform:
    needs: cd-admin-backend
    uses: ./.github/workflows/reusable-terraform-ci.yml
    with:
      terraform-path: 'iac/backend'

  cd-admin-backend-terraform:
    needs: ci-admin-backend-terraform
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-terraform-cd.yml
    with:
      terraform-path: 'iac/backend'
      env-vars: |
        {
          "ENV":"production",
          "REGION":"us-east-1",
          "DEBUG":"false"
        } 
      admin-backend-image-tag: ${{ needs.cd-admin-backend.outputs.image_tag }}
      branch-name: ${{ github.ref_name }}
    secrets:
      database-url: ${{ secrets.DATABASE_URL }}

