name: CI & CD Landing frontend terraform 

on:
  push:
    branches: [ master ]
    paths:
      - 'iac/public-frontend/landing/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'iac/public-frontend/landing/**'
  workflow_dispatch:

jobs:
  ci-landing-frontend-terraform:
    uses: ./.github/workflows/reusable-terraform-ci.yml
    with:
      terraform-path: 'iac/public-frontend/landing'

  cd-landing-frontend-terraform:
    permissions:
      id-token: write
      contents: read
    needs: ci-landing-frontend-terraform
    uses: ./.github/workflows/reusable-terraform-cd.yml
    with:
      branch-name: ${{ github.ref_name }}
      terraform-path: 'iac/public-frontend/landing'


