name: ci_cd_landing_frontend 

on:
  push:
    branches: [ master ]
    paths:
      - 'frontends/landing/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'frontends/landing/**'
  workflow_dispatch:

jobs:
  ci-landing-frontend:
    uses: ./.github/workflows/reusable-frontend-ci.yml
    with:
      frontend-path: 'frontends/landing'
      node-version: '20'

  cd-landing-frontend:
    permissions:
      id-token: write
      contents: read
    needs: ci-landing-frontend
    uses: ./.github/workflows/reusable-frontend-cd.yml
    with:
      frontend-path: 'frontends/landing'
      node-version: '20'
      cloudfront-distribution-id: 'E3PVFAZHMLAOA3'
      s3-bucket-url: 's3://production-menapp-landing-frontend'
      branch-name: ${{ github.ref_name }}
  
