name: CI Terraform

on:
  push:
    branches: [ main ]
    paths:
      - 'iac/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'iac/**'

jobs:
  ci-terraform:
    name: ci-terraform
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"

    - name: Terraform Format
      run: terraform fmt -check -recursive
      working-directory: iac

    - name: Terraform Init
      run: terraform init -backend=false
      working-directory: iac

