name: Reusable Terraform CD

on:
  workflow_call:
    inputs:
      terraform-path:
        description: 'Path to the frontend directory'
        required: true
        type: string
      env-vars:
        required: false
        description: 'json file of key pairs env vars'
        type: string
        default: ''
      branch-name:
        required: true
        description: 'current branch name'
        type: string
      database-url:
        description: 'database url'
        required: false
        type: string
      admin-backend-image-tag:
        description: 'admin backend image tag'
        required: false
        type: string
permissions:
  id-token: write
  contents: read
jobs:
  cd-terraform:
    if: inputs.branch-name == 'master' 
    name: cd-terraform
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::084519756118:role/GithubActions
        aws-region: us-east-1
        audience: "sts.amazonaws.com"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ inputs.terraform-path }}
      env:
        TF_VAR_DATABASE_URL: ${{ inputs.database-url }}
        TF_VAR_ADMIN_BACKEND_IMAGE_TAG: ${{ inputs.admin-backend-image-tag }}

    - name: Terraform Plan
      run: terraform plan 
      working-directory: ${{ inputs.terraform-path }}
      env:
        TF_VAR_DATABASE_URL: ${{ inputs.database-url }}
        TF_VAR_ADMIN_BACKEND_IMAGE_TAG: ${{ inputs.admin-backend-image-tag }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{ inputs.terraform-path }}
      env:
        TF_VAR_DATABASE_URL: ${{ inputs.database-url }}
        TF_VAR_ADMIN_BACKEND_IMAGE_TAG: ${{ inputs.admin-backend-image-tag }}

    - name: Terraform Output
      run: terraform output -json
      working-directory: ${{ inputs.terraform-path }}