name: Reusable Terraform CD

on:
  workflow_call:
    inputs:
      terraform-path:
        description: 'Path to the frontend directory'
        required: true
        type: string
      env-vars:
        required: false
        description: 'json file of key pairs env vars'
        type: string
        default: ''
      branch-name:
        required: true
        description: 'current branch name'
        type: string
permissions:
  id-token: write
  contents: read
jobs:
  cd-terraform:
    if: inputs.branch-name == 'master' 
    name: cd-terraform
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Parse env-vars JSON into $GITHUB_ENV
      if: inputs.env-vars != ''
      run: |
        echo '${{ inputs.env-vars }}' | base64 -d > tmp-env.json
        for key in $(jq -r 'keys[]' tmp-env.json); do
          value=$(jq -r ".\"$key\"" tmp-env.json)
          echo "$key=$value" >> $GITHUB_ENV
        done

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::084519756118:role/GithubActions
        aws-region: us-east-1
        audience: "sts.amazonaws.com"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ inputs.terraform-path }}
     
    - name: Terraform Plan
      run: terraform plan 
      working-directory: ${{ inputs.terraform-path }}
      
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{ inputs.terraform-path }}

    - name: Terraform Output
      run: terraform output -json
      working-directory: ${{ inputs.terraform-path }}