name: reusable_backend_cd

on:
  workflow_call:
    inputs:
      image-path:
        description: 'build context path (e.g., ./backend)'
        required: true
        type: string
      dockerfile-path:
        description: 'path to Dockerfile relative to build context (e.g., apps/admin-api/Dockerfile)'
        required: true
        type: string
      image-uri:
        description: 'image uri to upload ecr'
        required: true
        type: string
      branch-name:
        description: 'currente branch name'
        required: true
        type: string
      env-vars:
        required: false
        description: 'json file of key pairs env vars'
        type: string
        default: ''
    outputs:
      image-tag:
        description: "Generated image tag"
        value: ${{ jobs.cd-backend.outputs.image_tag }}
permissions:
  id-token: write
  contents: read
jobs:
  cd-backend:
    if: inputs.branch-name == 'master' 
    name: cd-backend
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.export-tag.outputs.image_tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Parse env-vars JSON into $GITHUB_ENV
      if: inputs.env-vars != ''
      run: |
        echo '${{ inputs.env-vars }}' | base64 -d > tmp-env.json
        for key in $(jq -r 'keys[]' tmp-env.json); do
          value=$(jq -r ".\"$key\"" tmp-env.json)
          echo "$key=$value" >> $GITHUB_ENV
        done

